---
version: "2.1"
services:
  davos:
    image: lscr.io/linuxserver/davos:latest
    container_name: davos
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Erope/Rome
    volumes:
      - /.docker/config/davos:/config
      - /path:/download
    ports:
      - 8080:8080
    restart: unless-stopped