---
version: "2.1"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Rome
    volumes:
      - /.docker/config/duplicati:/config
      - /path:/backups
      - /path:/source
    ports:
      - 8200:8200
    restart: unless-stopped
